import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/Colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    padding: 16,
    backgroundColor: COLORS.backgroundColor,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.textColor,
    flexShrink: 1,
  },
  input: {
    height: 40,
    borderColor: COLORS.borderColor,
    borderWidth: 1,
    marginBottom: 16,
    paddingHorizontal: 8,
    color: COLORS.textColor,
    backgroundColor: 'black',
    borderRadius: 6,
  },
  mainInput: {
    flex: 1,
    height: 40,
    borderColor: COLORS.borderColor,
    borderWidth: 1,
    color: COLORS.textColor,
    backgroundColor: 'black',
    borderRadius: 6,
    paddingHorizontal: 10,
  },
  mainInputContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    paddingRight: 10,
    width: '100%',
    marginBottom: 10,
  },
  inputContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    marginRight: 10,
  },
  nestedInput: {
    flex: 1,
    height: 40,
    borderColor: COLORS.borderColor,
    borderWidth: 1,
    paddingHorizontal: 8,
    color: COLORS.textColor,
    borderRadius: 6,
    marginBottom: 10,
  },
  mainAddButton: {
    padding: 10,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: 40,
    backgroundColor: 'green',
    borderRadius: 6,
    gap: 4,
    flexDirection: 'row',
  },
  addButton: {
    padding: 10,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: 40,
    backgroundColor: 'green',
    borderRadius: 6,
    gap: 4,
    flexDirection: 'row',
  },
  listItem: {
    width: '100%',
    height: 60,
    justifyContent: 'center',
    paddingHorizontal: 8,
    borderRadius: 6,
    marginBottom: 1,
  },
  listItemText: {
    color: COLORS.listItemTextColor,
    fontWeight: 'normal',
    fontSize: 16,
  },
  listObject: {
    backgroundColor: 'inherit',
  },
  listObjectText: { 
    color: COLORS.listObjectTextColor,
    fontWeight: 'bold',
    fontSize: 16,
    textTransform: 'capitalize',
  },
  nestedListItemText: {
    color: COLORS.nestedListItemTextColor,
    fontSize: 14,
  },
  dropdown: {
    paddingLeft: 10,
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: COLORS.headerBackgroundColor,
    borderLeftWidth: 1,
    borderLeftColor: COLORS.borderColor,
  },
  nestedListItem: {
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderColor,
  },
  deleteButtonParent: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    width: 100,
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 6,
  },
  deleteButton: {
    backgroundColor: COLORS.deleteButtonBackgroundColor,
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    display: 'flex',
    width: 94,
    left: 100,
    borderRadius: 6,
  },
  deleteButtonText: {
    color: COLORS.deleteButtonTextColor,
    fontWeight: 'bold',
  },
  addIcon: {
    marginLeft: 30,
    marginRight: 20,
  },
  editButtonParent: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: 100,
    paddingTop: 4,
    paddingBottom: 4,
    paddingRight: 4,
  },
  editButton: {
    backgroundColor: COLORS.editButtonBackgroundColor,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: 94,
    left: -100,
    borderRadius: 6,
  },
  leftAction: {
    backgroundColor: 'red', // Example color
    justifyContent: 'center',
    alignItems: 'center',
    width: 75,
  },
  actionText: {
    color: 'white',
    fontWeight: 'bold',
  },
  normalText: {
    fontWeight: 'normal',
    color: 'white',
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  flatListContentContainer: {
    paddingBottom: 100,
  },
  dropdownButton: {
    padding: 10,
    borderRadius: 5,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 75,
    borderWidth: 1,
  },
  actionButton: {
    backgroundColor: 'red', // Example color
    justifyContent: 'center',
    alignItems: 'center',
    width: 75,
  },
});

export default styles;
